version: "3"
name: "vdo-dev-db"

volumes:
  vdo_mysql_db:
    driver: local
  vdo_mysql_cnf:
    driver: local

services:
  mysql:
    image: mysql:8
    container_name: vdo_mysql
    network_mode: host
    volumes:
      - vdo_mysql_db:/var/lib/mysql
      - vdo_mysql_cnf:/etc/mysql/conf.d
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: abcd*1234
    privileged: true
    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password"
      ]
